---
driver:
  name: docker
  hostname: keepalived.ci.local
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: keepalived
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - keepalived
  pillars:
    top.sls:
      base:
        "*":
          - keepalived

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: keepalived_cluster
    provisioner:
      pillars-from-files:
        keepalived.sls: tests/pillar/keepalived_cluster.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
