{%- from "keepalived/map.jinja" import cluster with context %}
{%- if cluster.get('enabled', False) %}
server:
  alert:
    KeepalivedProcessDown:
      if: >-
        procstat_running{process_name="keepalived"} == 0
      {% raw %}
      labels:
        severity: major
        service: keepalived
      annotations:
        summary: 'Keepalived process is down'
        description: 'Keepalived process is down on node {{ $labels.host }}'
      {% endraw %}
    KeepalivedFailedState:
      if: >-
        keepalived_state == 0
      {% raw %}
      labels:
        severity: minor
        service: keepalived
      annotations:
        summary: 'Keepalived entered the FAILED state'
        description: 'Keepalived is in the FAILED state on node {{ $labels.host }}'
      {% endraw %}
{%- endif %}
